name: flutter_love
description: Provide flutter widgets handle common use case with love state management library
version: 0.1.0-beta.6
homepage: https://github.com/LoveCommunity/flutter_love

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  love: ^0.1.0-rc.2
  provider: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter