name: flutter_love
description: Provide flutter widgets handle common use case with love state management library
version: 0.2.0
homepage: https://github.com/LoveCommunity/flutter_love

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  love: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1